### PR TITLE
Link to GUI .bin editor in README as additional tool.

### PR DESCRIPTION
**Pull request by kapilpokhrel**
I had recently worked on a GUI tool to edit .bin file. So I thought it might be helpful to link here.

### CODE REVIEW

**Comment by BTEST4HE** [comment]
Approved.
Thanks for creating a great tool.

**Comment by kapilpokhrel** [comment]
> Approved.
> Thanks for creating a great tool.

Thanks for the approval.
And, since you have way more knowledge in this stuff, I was hoping maybe you could go through the code (it's messy) and validate it ( I might have been wrong somewhere while parsing the file. )

**Comment by BTEST4HE** [comment]
> 
> Thanks for the approval. And, since you have way more knowledge in this stuff, I was hoping maybe you could go through the code (it's messy) and validate it if it's ok with you. ( I might have been wrong somewhere while parsing the file. )

Looking at the source code, I think the interpretation of the pmb.bin file is correct.
I also tried the mod using GT3PMBBINEditor and the images were displayed correctly and worked without any problems, so I think this will work.

**Comment by kapilpokhrel** [comment]
Cool!
Also, do you have any knowledge about the .inf music files? Me and my friend are working on it and we have mostly figured it out except one piece of data. So, maybe you can help if you know about it?

**Comment by BTEST4HE** [comment]
Sorry, I have no idea about the structure of .inf files, and if I were to do it, I would want to analyze mbl and pmb, so I won't.

**Pull request merged**
